# Generated by Django 5.0.6 on 2026-08-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cover_url',
            field=models.URLField(blank=True),
        ),
    ]
